version: 2
jobs:
  build:
    docker:
    # rubyの実行イメージ
    - image: circleci/ruby:2.5.0-node-browsers
      environment:
        RAILS_ENV: test
        MYSQL_DATABASE: 'qiita_clone_test'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ''
    # mysqlの実行イメージ
    - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Rubocop Check
    - run:
        name: RuboCop Style Check
        command: bundle exec rubocop

    # テストデータベースの設定
    - run: rm ./config/database.yml
    - run: mv ./config/database.yml.ci ./config/database.yml
    - run: bundle exec rake db:create RAILS_ENV=test
    - run: bundle exec rake db:migrate RAILS_ENV=test

    # run tests!
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

          bundle exec rspec --require rails_helper \
                          --format documentation \
                          --color \

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results